### ISSUE TITLE
I think Marx also fits the criteria for this list

### ISSUE THREAD

**Issue by mblode** [ubershmekel/cssbed#1]
Here is the URL to the Marx repo: https://github.com/mblode/marx

Marx - The classless CSS reset (perfect for Communists).

Marx is a CSS stylesheet to be used in any projects (namely small ones). If you don't need the weight of heavy frameworks or you would just like to make an edible website quickly, Marx is perfect for you. It can be used out of the minified box but it can also be customised and styled through the use of HTML classes.

**Comment by ubershmekel** [comment]
Thanks for making Marx and suggesting it. I added it and had a good chuckle from the subtitle.

**Comment by mblode** [comment]
Haha glad you liked it! 😆 I think I came up with the name and worked backwards to make a framework without classes

**Comment by mblode** [comment]
I wonder if there should be a max-width of 700px (?) that are standardised across each of the styles.
Marx specifically uses a `<main>` tag to set the width where others set this in the `<body>` tags

**Comment by ubershmekel** [comment]
@mblode my thinking was to have zero CSS in the shared template. Completely relying on the snippet to style everything. So no explicit 700px.

About having a `<main>` tag - that seems to fix Bahunya as well and doesn't impact anything else. Is there a tradeoff? What else can there be besides `<main>` or is it always the one node under `body`?

**Comment by ubershmekel** [comment]
I see on the Marx site there is a `<nav>`. I wonder if I should add one to the cssbed too...

**Comment by mblode** [comment]
I just saw this discussion on Hacker News today about whether you target the body or main/container with a max-width. In my mind some elements such as the nav should have the option to expand the full-width (as seen on the demo). There is probably no need for a `nav` on CSS bed, however, as I can only imagine that it would be extremely inconsistently styled across each stylesheet. But if you could add a `main` tag nested below body, that would help out the layout of Marx, Bahunya, and probably some future styles.

**Comment by ubershmekel** [comment]
@mblode I added it. Thanks for the note.
