### ISSUE TITLE
wrong link for vanillacss.com

### ISSUE THREAD

**Issue by jablka** [ubershmekel/cssbed#13]
in `vanillacss` directory, there is actually a wrong link to `sakura css` instead of https://vanillacss.com/

This is also in the production site: https://www.cssbed.com/vanillacss/ . See the href link attribute under '_Source behind this one_'.

**Comment by Cacilie** [comment]
PR to fix issue:
https://github.com/ubershmekel/cssbed/pull/14

**Comment by Cacilie** [comment]
PR MERGED. Issue fixed. I think we can close the issue @ubershmekel
