### ISSUE TITLE
Table Issue on water.css dark theme

### ISSUE THREAD

**Issue by QuentinDela** [ubershmekel/cssbed#2]
<img width="345" alt="Screen Shot 2019-04-07 at 2 19 27 PM" src="https://user-images.githubusercontent.com/12401728/55683446-3b595500-5940-11e9-8b2a-3af93564f33f.png">

**Comment by ubershmekel** [comment]
@QuentinDela what's the problem?

**Comment by mblode** [comment]
It looks like a text alignment issue on the `th` tags and probably a padding issue. @QuentinDela maybe open an issue on water.css' GitHub repo
